### ISSUE TITLE
Issue running 'cargo run'

### ISSUE THREAD

**Issue by unsigned-long-long-int** [Rahix/avr-hal-template#18]
I had encountered an error while trying to run the code. This is an exact copy from the terminal output:
```
➜  blink cargo run                                                                            
warning: unused config key `build.runner` in `/home/eli/blink/.cargo/config.toml`
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
    Finished dev [optimized + debuginfo] target(s) in 15.41s
     Running `target/avr-atmega328p/debug/ard.elf`
target/avr-atmega328p/debug/ard.elf: 1: Syntax error: word unexpected (expecting ")")
➜  blink 
```
I have no clue what is happening or why it isn't working. If anyone can help me, it would be greatly appreciated!

**Comment by Rahix** [comment]
Hi, please provide a bit more context on this:

- OS & Distribution
- `avr-binutils` version
- `avr-gcc` version
- What is that `blink` prefix command?
- cargo version
- rustc version

Beyond that, that very first warning is already suspicious.  Why would cargo ignore the configured runner?

**Comment by ghost** [comment]
The os is Linux Mint
All of the packages are up-to-date and on stable branch except for avr-binutils as apt couldn't find it.
I use zsh, so blink is the name of the folder. The folder name is printed after the arrow.
I couldn't use crgo-generate because it wouldn't install. I could email you a copy of the files I used. Sorry if my typing is bad! I am on my phone!

**Comment by ghost** [comment]
It was fixed! I still dont know what the issue was.

**Comment by Rahix** [comment]
Hm, odd.  Let's close this issue then and reopen if it happens again for someone.
